export const getRedisKeys = (roomName) => ({
  INFO: `live:${roomName}:info`,
  VIEWERS: `live:${roomName}:viewers`,
  PEAK_VIEW: `live:${roomName}:peak`,
  AVG_RATE: `live:${roomName}:avg_rate`,
  STAY_MINUTE: `live:${roomName}:stay`,
  ALL_VISITORS: `live:${roomName}:all_visitors`,
  REVISIT: `live:${roomName}:revisit`,
  CATEGORY: `live:${roomName}:category`,
  TIMESERIES: `live:${roomName}:timeseries`,
  HIGHLIGHTS: `live:${roomName}:highlights`,
  DONATION: `live:${roomName}:donation`,
  DONATION_TOTAL_AMOUNT: `live:${roomName}:donation:total`,
  DONATION_COUNT: `live:${roomName}:donation:count`,
  DONATION_TIMESERIES: `live:${roomName}:donation:timeseries`,
  DONATION_UNIQUE_USERS: `live:${roomName}:donation:users`,
  CHAT_UNIQUE_USERS: `live:${roomName}:chat:users`,
  CHAT_TIMESERIES: `live:${roomName}:chat:timeseries`,
  VIEWER_RANK: `live:rank`,
  MSG: `live:${roomName}:msg`,
  EGRESS: `live:${roomName}:egress`,
});
