export const MAIN_BANNER_SLIDE_DURATION = 4000;
export const MAIN_BANNER_VIDEO_DURATION = 240;
export const MAIN_BANNER_VISIBLE_COUNT = 3;
export const MAIN_BANNER_CAROUSEL_CARD_WIDTH = 128;
export const MAIN_BANNER_CAROUSEL_CARD_MARGIN_RIGHT = 128;
